export 'package:flutter_getx/views/screens/HomeScreen.dart';
export 'package:flutter_getx/views/screens/MainScreen.dart';
export 'package:flutter_getx/views/screens/ReactiveScreen.dart';
export 'package:flutter_getx/views/screens/ThirdReactiveScreen.dart';
export 'package:flutter_getx/views/screens/ForthReactiveScreen.dart';
export 'package:flutter_getx/views/screens/LocalizedScreen.dart';
export 'package:flutter_getx/views/screens/ServiceScreen.dart';
export 'package:flutter_getx/views/screens/ProductsScreen.dart';
export 'package:flutter_getx/views/screens/GetStorageScreen.dart';
